FIND_PATH(TINYXML2_INCLUDE_DIR tinyxml2.h /usr/include /usr/local/include)

FIND_LIBRARY(TINYXML2_LIBRARY NAMES tinyxml2 PATH /usr/lib /usr/local/lib)

IF(TINYXML2_INCLUDE_DIR AND TINYXML2_LIBRARY)
	SET(TINYXML2_FOUND TRUE)
ENDIF(TINYXML2_INCLUDE_DIR AND TINYXML2_LIBRARY)

IF(TINYXML2_FOUND)
	IF(NOT TINYXML2_FIND_QUIETLY)
		MESSAGE(STATUS "Found TinyXML2: ${TINYXML2_LIBRARY}")
	ENDIF(NOT TINYXML2_FIND_QUIETLY)
ELSE(TINYXML2_FOUND)
	IF(TINYXML2_FIND_REQUIRED)
		IF(NOT TINYXML2_INCLUDE_DIR)
			MESSAGE(FATAL_ERROR "Could not find TinyXML2 header file!")
		ENDIF(NOT TINYXML2_INCLUDE_DIR)

		IF(NOT TINYXML2_LIBRARY)
			MESSAGE(FATAL_ERROR "Could not find TinyXML2 library files!")
		ENDIF(NOT TINYXML2_LIBRARY)
	ENDIF(TINYXML2_FIND_REQUIRED)
ENDIF(TINYXML2_FOUND)
